### ISSUE TITLE
А как с отрицательными числами быть?

### ISSUE THREAD

**Issue by volodink** [neverkor/labi#2]
https://github.com/neverkor/labi_python/blob/077965f1d9a5de9f7019ce8cf49c331edd65c3e8/laba3.py#L7

**Comment by neverkor** [comment]
Он нормально их распознает. Ввожу минимальное -2 максимальное -7, к примеру, он ругается что мин значение больше максимального. Все верно вроде.

**Comment by volodink** [comment]
Понял. Вычеркиваем.

13 февр. 2018 г. 9:51 AM пользователь "neverkor" <notifications@github.com>
написал:
