### ISSUE TITLE
Разбейте на фукции и модули код 8 лабы. Тут задание такое.

### ISSUE THREAD

**Issue by volodink** [neverkor/labi#5]
https://github.com/neverkor/labi_python/blob/84402f95b9f8fa2d58d3102cb4cbd583849d3307/laba8.py#L9

**Comment by neverkor** [comment]
Разбил на функции.

**Comment by neverkor** [comment]
Разбить на модули это т. е. на несколько файлов?

**Comment by volodink** [comment]
Да.

20 февр. 2018 г. 5:47 PM пользователь "neverkor" <notifications@github.com>
написал:

**Comment by volodink** [comment]
Создать функции и модули.

20 февр. 2018 г. 5:47 PM пользователь "neverkor" <notifications@github.com>
написал:

**Comment by neverkor** [comment]
разбил на модули в отдельной папке laba8_modules
